#!/usr/bin/env python3
"""Write courses/<CODE>/myst.yml — one MyST book per course (run after editing course list)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSES = ROOT / "courses"

# (code, title, description line)
DATA: list[tuple[str, str, str]] = [
    ("AINS-M6001", "Personal Attention & Influence Systems", "Executable self-influence model — notebooks, SAMWISE, faculty defense."),
    ("AINS-M6002", "Audience Worlds", "Simulated audience populations and emergence from rules."),
    ("AINS-M6003", "Positioning & Narrative Systems", "Positioning and narrative as testable mechanisms."),
    ("AINS-M6004", "Brand as Dynamic System", "Brand as state under shocks and creative dynamics."),
    ("AINS-M6005", "Channel & Content Economics", "Reach, cost, conversion across major platform families."),
    ("AINS-M6006", "Measurement, Privacy & Compliance", "Measurement, consent, and policy as constraints."),
    ("AINS-M6101", "Campaign Orchestration", "Multi-touch campaign simulation across ecosystems."),
    ("AINS-M6102", "Creative Testing at Scale", "Experiment systems — lift, variance, stopping rules."),
    ("AINS-M6103", "Data-Driven Marketing & Attribution", "Attribution, data workflows, retrieval and evaluation."),
    ("AINS-M6104", "Partnerships & Ecosystem", "Partners and affiliates as incentive-carrying agents."),
    ("AINS-M6105", "Growth Loops & Community", "Loops and community as reinforced feedback."),
    ("AINS-M6106", "Crisis & Reputation Stress Tests", "Adversarial reputation and fragility analysis."),
    ("AINS-M6201", "Competitive Narrative Arena", "Competing world models and strategic interaction."),
    ("AINS-M6202", "Strategy as Marketing Policy", "Strategy encoded as policy under uncertainty."),
    ("AINS-M6203", "Budget & Portfolio Allocation", "Budget and risk across initiatives."),
    ("AINS-M6204", "Autonomous Marketing Systems", "Governed automation with human-in-the-loop boundaries."),
    ("AINS-M6205", "Ethics, Influence & Control", "Alignment, governance, and oversight of influence."),
    ("AINS-M6206", "Magisterium Thesis (Marketing)", "Capstone — deploy, validate, document, defend."),
]

HUB_ACTION_URL = "https://magisterium.castalia.institute/magai/marketing/"


def myst_yaml(code: str, title: str, description: str) -> str:
    d = COURSES / code
    has_nb = d.joinpath("notebooks").is_dir() and any(d.joinpath("notebooks").iterdir())
    has_sw = d.joinpath("samwise").is_dir() and any(d.joinpath("samwise").glob("*.md"))

    toc_lines = [
        "  toc:",
        "    - file: SYLLABUS.md",
        "    - pattern: lectures/*.md",
    ]
    if has_sw:
        toc_lines.append("    - pattern: samwise/*.md")
    if has_nb:
        toc_lines.append("    - pattern: notebooks/*.ipynb")

    extra = ""
    if code == "AINS-M6001":
        extra = """
    - title: Instructor deck
      children:
        - file: ../../slides/ains-m6001_lecture01_intro.md
    - title: Exercises
      children:
        - file: ../../exercises/ains-m6001/warmup.md
        - file: ../../exercises/ains-m6001/mcp_tool_design.md"""

    return f"""# Generated by scripts/generate_course_myst.py — course book ({code})
version: 1
project:
  title: "{code}: {title}"
  description: "{description}"
  keywords:
    - marketing
    - artificial intelligence
    - Castalia
    - Magisterium
    - "{code}"
  exclude: []
{chr(10).join(toc_lines)}{extra}
site:
  template: book-theme
  options:
    logo_text: "{code}"
    style: ../../styles/site.css
  actions:
    - title: Mag.AI-Marketing (program)
      url: {HUB_ACTION_URL}
"""


def main() -> None:
    for code, title, desc in DATA:
        out = COURSES / code / "myst.yml"
        if not (COURSES / code).is_dir():
            raise SystemExit(f"Missing directory: {COURSES / code}")
        out.write_text(myst_yaml(code, title, desc), encoding="utf-8")
        print("wrote", out.relative_to(ROOT))


if __name__ == "__main__":
    main()
